version: "3.9"
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgress-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: "Asia/Tokyo"
      PGTZ: "Asia/Tokyo"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /aws-api
    init: true
    tty: true
    stdin_open: true
    volumes:
      - .:/aws-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}

# vendor/bundleはvolumesにマウントしていない
volumes:
  postgress-data:
